apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    day2operation.app.stacks/targetKinds: Pod
  name: runtimeoperations.app.stacks
spec:
  additionalPrinterColumns:
  - JSONPath: .status.conditions[?(@.type=='Started')].status
    description: Indicates if runtime operation has started
    name: Started
    type: string
  - JSONPath: .status.conditions[?(@.type=='Started')].reason
    description: Reason for runtime operation failing to start
    name: Reason
    priority: 1
    type: string
  - JSONPath: .status.conditions[?(@.type=='Started')].message
    description: Message for runtime operation failing to start
    name: Message
    priority: 1
    type: string
  - JSONPath: .status.conditions[?(@.type=='Completed')].status
    description: Indicates if runtime operation has completed
    name: Completed
    type: string
  - JSONPath: .status.conditions[?(@.type=='Completed')].reason
    description: Reason for runtime operation failing to complete
    name: Reason
    priority: 1
    type: string
  - JSONPath: .status.conditions[?(@.type=='Completed')].message
    description: Message for runtime operation failing to complete
    name: Message
    priority: 1
    type: string
  group: app.stacks
  names:
    kind: RuntimeOperation
    listKind: RuntimeOperationList
    plural: runtimeoperations
    shortNames:
    - runtimeop
    - runtimeops
    singular: runtimeoperation
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: RuntimeOperation is the Schema for the runtimeoperation API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: RuntimeOperationSpec defines the desired state of RuntimeOperation
          properties:
            command:
              description: Command to execute. Not executed within a shell
              items:
                type: string
              type: array
            containerName:
              description: Name of the container. Defaults to main container "app"
              type: string
            podName:
              description: Name of the Pod to perform runtime operation on. Pod must
                be from the same namespace as the RuntimeOperation instance
              type: string
          required:
          - command
          - podName
          type: object
        status:
          description: RuntimeOperationStatus defines the observed state of RuntimeOperation
          properties:
            conditions:
              items:
                description: OperationStatusCondition ...
                properties:
                  lastTransitionTime:
                    format: date-time
                    type: string
                  lastUpdateTime:
                    format: date-time
                    type: string
                  message:
                    type: string
                  reason:
                    type: string
                  status:
                    type: string
                  type:
                    description: OperationStatusConditionType ...
                    type: string
                type: object
              type: array
          type: object
  version: v1beta1
  versions:
  - name: v1beta1
    served: true
    storage: true
